Portfolio: setup and mobile first
sibabalwemosia24/Microverse_Portfolio pull request #1
Opened 2022-08-24 09:04 UTC by sibabalwemosia24

# Description
The first milestone in creating my portfolio website
## General requirements
Make sure there are no linter errors.
Use the correct Gitflow
Document work professionally
## Project requirements
Use HTML&CSS linters
Build toolbar and headline section

2022-08-24 14:41 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @sibabalwemosia24 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳✨🧨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️

- [ ] Please try to make sure that your website closely resembles the Figma Design. This includes the font size, font weights, colors, margins, and so on. So kindly update your design to resemble the Figma Design as closely as possible 🤗

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +            <h2 class="logo"><a href="#">My Logo</a></h2>
Kindly remove the underline from the logo as shown in the Figma Design 😀
Also, kindly align the logo and hamburger menu in the middle 😊

Your design:
![image](https://user-images.githubusercontent.com/73714615/186441810-69b5bdbe-bfd2-47ea-8c2a-f57e09f92893.png)

Figma Design:
![image](https://user-images.githubusercontent.com/73714615/186441738-80a30413-5c97-465a-9888-5b598dfeab9f.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +            </div>
Instead of wrapping the whole header in a `<nav>` tag, it would be better to only wrap the hamburger menu in the `<nav>`tag 🤗

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +    </header>
Kindly make sure that your header design is responsive and fills the entire width of the screen as shown in Figma. You can use `flex-box` to achieve responsive designs 😃

Your design:
![image](https://user-images.githubusercontent.com/73714615/186442998-715b3586-094c-44bc-84d8-594c15fcb539.png)

Figma Design:
![image](https://user-images.githubusercontent.com/73714615/186443053-478cabea-30bf-4d17-bc3a-e248ec83738e.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +            <h2 class="logo"><a href="#">My Logo</a></h2>
Kindly note that the color of your logo is being overridden by the default color of the `<a>` tag. Kindly fix that by removing the default decoration of the `<a>` tag 😃
![image](https://user-images.githubusercontent.com/73714615/186443759-39389bb4-d379-409c-ba76-c397af5cffd4.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +        </section>
Kindly note that you should make your design responsive using flex-box as described in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md#project-requirements)  😃

Your design:
![image](https://user-images.githubusercontent.com/73714615/186444156-26b09b2e-d8b8-452d-b404-f70fadf36b28.png)

Figma Design:
![image](https://user-images.githubusercontent.com/73714615/186444232-0747657a-5e50-45d2-bd6c-a5726f93a409.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +            <h2 class="greeting">I'm Sibabalwe Glad to see you</h2>
Kindly use an `h1` tag for this since this is the main heading of your webpage 🤗 If you need more information, check this [link](https://www.reliablesoft.net/h1-tag/).
You should also update the font size, weight, and color of this heading to match the Figma Design.

Your design:
![image](https://user-images.githubusercontent.com/73714615/186445632-c113d4ab-6790-4139-a2ca-30c5131853e7.png)

Figma Design:
![image](https://user-images.githubusercontent.com/73714615/186445815-fa7da594-6c14-44a5-9e82-981b37f7f641.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +            <h4 class="contact">LET'S CONNECT</h4>
Kindly update the font size, weight, and color of these two tags to match the Figma Design 😃

Your design:
![image](https://user-images.githubusercontent.com/73714615/186446119-61b2b138-eaf0-45ab-9b9a-d54f40affc32.png)

Figma design:
![image](https://user-images.githubusercontent.com/73714615/186446163-49c42547-286a-4460-ba69-71d0bdc891d3.png)

2022-08-24 14:41 UTC, awais-amjed commented on index.html
> +                </ul>
Kindly note that in the Figma design these social icons are in a horizontal orientation instead of a vertical one. Please fix that 🤗

Your design:
![image](https://user-images.githubusercontent.com/73714615/186446510-361405bd-1fad-4f51-ae3e-376a72cd7328.png)

Figma Design:
![image](https://user-images.githubusercontent.com/73714615/186446557-57770336-f834-4fc1-8522-6bd1e35fba05.png)

2022-08-24 14:41 UTC, awais-amjed commented on README.md
> +
I can see that you have made a good effort to make a Readme like Microverse 👏👏 but kindly note that you need to use the Readme file from [Microverse Readme Template](https://github.com/microverseinc/readme-template/blob/master/README.md) and update it according to your project 🤗

2022-08-25 10:01 UTC, Bondok6 requested changes
Hi @sibabalwemosia24 🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 ## Highlights
- No Linter errors ✅
- Well file structure ✅
- Using Gitflow correctly ✅

 ## Required Changes ♻️
 - [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:08 UTC, aimemalaika approved these changes
Hi @sibabalwemosia24 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:25 UTC, merged